### ISSUE TITLE
Fix: The apache main guy

### ISSUE THREAD

**Issue by MohamedAlDeep** [Thatguy553/A3-Custom-Missions#8]
the guy has stop sign in his hand

**Comment by MohamedAlDeep** [comment]
![image](https://github.com/Thatguy553/A3-Custom-Missions/assets/95958815/50e6e672-4ce3-41d1-b627-61f4bc0873fd)

**Comment by MohamedAlDeep** [comment]
changed the name also fixed the guy but he doesnt look the same

**Comment by MohamedAlDeep** [comment]
![image](https://github.com/Thatguy553/A3-Custom-Missions/assets/95958815/01632520-30a1-426a-a038-54d73f91bae9)

**Comment by Thatguy553** [comment]
ah yeah I did that, I was checking what was added by another mod, ill revert him once I begin working again today.
